### ISSUE TITLE
Incorrect Scan of the ICCID Number to Activate SIM

### ISSUE THREAD

**Issue by interested1** [particle-iot/particle-tinker-app-ios#14]
Scanning a Telefonica SIM card with the cell camera returns the correct number, but adds text to the field and makes the ICCID invalid. 

The expected behavior is that scanning the card returns only the ICCID number.

The issue is that scanning returns the ICCID number surrounded by text.
`Optional("####")` where #### is the correct number

**Comment by RaimundasSakalauskas** [comment]
This has been fixed in commit 5786f5d8ca9780f9fe8924e6d26de47dfc600d19.
