### ISSUE TITLE
Does not build under Xcode 9.2

### ISSUE THREAD

**Issue by gitjoost** [particle-iot/particle-tinker-app-ios#15]
Generates error: 
Showing Recent Messages
(null): could not read data from '~/Library/Mobile Documents/com~apple~CloudDocs/github/particle/photon-tinker-ios/Pods/Target Support Files/1PasswordExtension/ResourceBundle-OnePasswordExtensionResources-Info.plist': The file “ResourceBundle-OnePasswordExtensionResources-Info.plist” couldn’t be opened because there is no such file.

**Comment by RaimundasSakalauskas** [comment]
I'm not receiving this error right now, but will try a fresh clone to make sure it compiles after all outdated dependencies are fixed.

**Comment by RaimundasSakalauskas** [comment]
I tried this again. Repo did compile with no errors after doing the following:

1. Fresh clone
1. `pod install`
1. Adding `Keys.swift` to Photon-Tinker folder.
1. Adding `GoogleService-Info.plist` to Photon-Tinker folder. 

Will update documentation on how to obtain these files & values used in them.
