### ISSUE TITLE
mobile app recommends user press "MODE" button on photon should be "SETUP"

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/particle-tinker-app-ios#2]

**Comment by suda** [comment]
Just got some people being confused about this during a workshop. Can we override [SparkSetupCustomization.m](https://github.com/spark/spark-setup-ios/blob/b98836430f7901fa4408e7650ee42979ba5bfaf4/Classes/User/SparkSetupCustomization.m#L56) depending on device which is being set up?

**Comment by idokleinman** [comment]
The device setup lib supports Photon only (Soft AP).. I can fix the text to say 'setup' instead of mode

**Comment by suda** [comment]
Oh, than yeah, changing it would fix it :) Thx Ido!

**Comment by monkbroc** [comment]
Charlie ran into this today as well.

**Comment by idokleinman** [comment]
Fixed
