### ISSUE TITLE
App v1.5 allows 'stealing' device

### ISSUE THREAD

**Issue by steelydev** [particle-iot/particle-tinker-app-ios#3]
I think it is a huge problem allowing the user of this app to transfer a device from one Particle Account to another without forcing the FROM account to release the device:
![img_0452](https://cloud.githubusercontent.com/assets/3296929/10195230/8e3e5440-675a-11e5-8696-4173f041fd95.PNG)

**Comment by zsup** [comment]
Hi @steelydev - this is a change that we actively made on the Photon (in comparison to the Core before it). We had tons of complaints about Cores being difficult to transfer from one person to another, so we decided to make it easy to pass ownership back and forth. In this new model, "physical ownership means virtual ownership" - in other words, if you have physical access to the device (specifically the SETUP button) then you can own the device.

This obviously doesn't work great for applications that require a high level of security, and so we are planning on implementing an optional "secured" version of the process that will require permission from the previous owner to transfer the device (more like the Core).
