### ISSUE TITLE
isAuthenticated not found on object of type SparkCloud

### ISSUE THREAD

**Issue by woxaixni** [particle-iot/particle-tinker-app-ios#4]
everything when it have "if ([SparkCloud sharedInstance].isAuthenticated)" throw me an error
****_error**_**
 /Users/VICE/Downloads/photon-tinker-ios-master/Pods/SparkSetup/Classes/UI/SparkGetReadyViewController.m:66:37: Property 'isAuthenticated' not found on object of type 'SparkCloud *'

---

also on
SparkDiscoverDeviceViewController.m#430  [SparkCloud sharedInstance].isAuthenticated
SparkSetupMainController.m#96  [SparkCloud sharedInstance].isAuthenticated 
how can i fixed that. thanks
running SDK ios9.2

**Comment by idokleinman** [comment]
This is Work In Progress (in Cloud SDK repo)
please use latest official 0.4 pod version release, not latest master branch tip.
