### ISSUE TITLE
Xcode build failed for Particle photon tinker iOS

### ISSUE THREAD

**Issue by ghost** [particle-iot/particle-tinker-app-ios#7]
Got source from: Github > spark/photon-tinker-ios > Releases > v1.6_appstore

Tried to build on Xcode 7.3.1 on OS X El Capitan 10.11.6 MacBook Pro

Got build error: "Command failed due to signal: Segmentation fault: 11"

Maybe this is an Xcode 7 Swift v2.

**Comment by idokleinman** [comment]
Did you try to install pods as frameworks? That might cause it because pods I use in this project are still in Obj-C

**Comment by ghost** [comment]
I have not installed pods.  Ah, hah!  Actually, I'm presently wrestling with installing the pods to support the SDK.  So, I assume they'll support Tinker v1.6 as well.  Thanks!
